[project]
name = "aerostack2"
version = "1.1.3"
description = "Aerostack2 - ROS2 framework for autonomous aerial robotics"
channels = ["conda-forge", "robostack-staging"]
platforms = ["osx-arm64", "linux-64", "osx-64"]

[tasks]
# Setup environment variables
setup-env = """
export AEROSTACK2_PATH=$PWD
export AEROSTACK2_WORKSPACE=$PWD
export ROS_DISTRO=humble
echo "Environment variables set:"
echo "  AEROSTACK2_PATH=$AEROSTACK2_PATH"
echo "  AEROSTACK2_WORKSPACE=$AEROSTACK2_WORKSPACE"
echo "  ROS_DISTRO=$ROS_DISTRO"
"""

# Build all packages (overridden by platform-specific tasks below)
build = "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=$(which python) -DPython_EXECUTABLE=$(which python)"
# Build single package with debug and warnings
build-pkg = "sh -c 'colcon build --packages-select \"$0\" --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=\"-Wall\" -DPython3_EXECUTABLE=$(which python) -DPython_EXECUTABLE=$(which python)'"
clean = "rm -rf build install log"

# Platform-specific builds
[target.osx-arm64.tasks]
build = "colcon build --symlink-install --packages-skip as2_gazebo_assets --cmake-args -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=$(which python) -DPython_EXECUTABLE=$(which python)"

[dependencies]
# Build tools
colcon-common-extensions = "*"
cmake = "*"
pkg-config = "*"
make = "*"
geographiclib-cpp = "*"
eigen = "*"
yaml-cpp = "*"
# ROS 2 Humble dependencies from robostack-staging
ros-humble-ros-base = "*"
ros-humble-ament-cmake = "*"
ros-humble-ament-cmake-python = "*"
ros-humble-rosidl-default-generators = "*"
ros-humble-rosidl-default-runtime = "*"
ros-humble-geographic-msgs = "*"
ros-humble-geometry-msgs = "*"
ros-humble-std-msgs = "*"
ros-humble-sensor-msgs = "*"
ros-humble-nav-msgs = "*"
ros-humble-trajectory-msgs = "*"
ros-humble-visualization-msgs = "*"
ros-humble-tf2 = "*"
ros-humble-tf2-ros = "*"
ros-humble-rclcpp = "*"
ros-humble-rclpy = "*"
ros-humble-image-transport = "*"
ros-humble-cv-bridge = "*"
ros-humble-diagnostic-msgs = "*"
ros-humble-bond = "*"
ros-humble-action-msgs = "*"

# Python dependencies
python = "3.11.*"
numpy = ">=1.26.4,<2"
pyyaml = "*"
setuptools = "*"
pip = "*"

# Note: Full ROS 2 Humble support on macOS ARM64 is limited
# Simulation packages (as2_gazebo_assets) are automatically skipped on macOS
# Use Docker or Linux for full simulation functionality
[target.linux-64.dependencies]
ros-humble-ros-gz = "*"
ros-humble-ros-gz-sim = "*"
ros-humble-ros-gz-bridge = "*"
ros-humble-ros-gz-interfaces = "*"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[feature.dev]
dependencies = { pytest = "*", flake8 = "*" }
