package:
  name: "ros-humble-as2-core"
  version: "1.1.3"

source:
  path: ..
  filter:
    include:
      - "as2_core/**"

build:
  number: 1
  skip: false
  script:
    - cmake -S as2_core -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=$PYTHON -DPython_EXECUTABLE=$PYTHON
    - cmake --build build
    - cmake --install build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - colcon-common-extensions
    - ros-humble-ament-cmake
    - ros-humble-rosidl-default-generators
    - ros-humble-ament-cmake-lint-cmake
    - ros-humble-ament-cmake-xmllint
    - ros-humble-ament-lint-auto
    - ros-humble-rmw-fastrtps-cpp
    - ros-humble-as2-msgs
  host:
    - ros-humble-ament-cmake
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-rclcpp-action
    - ros-humble-std-msgs
    - ros-humble-nav-msgs
    - ros-humble-sensor-msgs
    - ros-humble-as2-msgs
    - ros-humble-std-srvs
    - ros-humble-geometry-msgs
    - ros-humble-geographic-msgs
    - ros-humble-tf2
    - ros-humble-tf2-ros
    - ros-humble-tf2-geometry-msgs
    - ros-humble-image-transport
    - ros-humble-cv-bridge
    - ros-humble-rmw-fastrtps-cpp
    - ros-humble-as2-msgs
    - geographiclib-cpp
    - yaml-cpp
    - eigen
    - pybind11

tests:
  - script: exit 0

about:
  homepage: "https://github.com/aerostack2/aerostack2"
  summary: "Aerostack2 core package which contains the basic classes of the Aerostack2 framework"
  license: "BSD-3-Clause"
