package:
  name: "ros-humble-as2-alphanumeric-viewer"
  version: "1.1.3"
source:
  path: ..
  filter:
    include:
      - "as2_alphanumeric_viewer/**"
build:
  number: 1
  skip: false
  script:
    - cmake -S as2_alphanumeric_viewer -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=$PYTHON
    - cmake --build build
    - cmake --install build
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - ros-humble-ament-lint-auto
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-python
    - ros-humble-as2-core
    - ros-humble-as2-msgs
    - ros-humble-rclcpp-lifecycle
    - ros-humble-rclpy
    - ros-humble-tf2-geometry-msgs
  run:
    - ros-humble-rclpy
    - ros-humble-as2-core
    - ros-humble-as2-msgs
    - ros-humble-tf2-geometry-msgs
about:
  homepage: "https://github.com/aerostack2/aerostack2"
  summary: "Aerostack2 motion reference handlers package"
  license: "BSD-3-Clause"
