package:
  name: "ros-humble-as2-msgs"
  version: "1.1.3"

source:
  path: ..
  filter:
    include:
      - "as2_msgs/**"


build:
  number: 1
  skip: false
  script:
    - colcon build --packages-select "as2_msgs" --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=$PYTHON -DPython_EXECUTABLE=$PYTHON

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make # [not win]
    - ninja # [win]
    - colcon-common-extensions
    - ros-humble-ament-cmake
    - ros-humble-rosidl-default-generators
    - ros-humble-ament-cmake-lint-cmake
    - ros-humble-ament-cmake-xmllint
  host:
    - ros-humble-ament-cmake
    - ros-humble-rclcpp
    - ros-humble-std-msgs
    - ros-humble-geometry-msgs
    - ros-humble-geographic-msgs
    - ros-humble-nav-msgs
    - ros-humble-action-msgs
    - ros-humble-sensor-msgs
  run:
    - ros-humble-rclcpp
    - ros-humble-std-msgs
    - ros-humble-geometry-msgs
    - ros-humble-geographic-msgs
    - ros-humble-nav-msgs
    - ros-humble-action-msgs
    - ros-humble-sensor-msgs
    - ros-humble-rosidl-default-runtime

tests:
  - script: exit 0

about:
  homepage: "https://github.com/aerostack2/aerostack2"
  summary: "Messages, services and action files for the AS2 stack"
  license: "BSD-3-Clause"

extra:
  recipe-maintainers:
    - alvaro-a-s
