name: Build packages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: macos-latest
            target-platform: osx-arm64
          - os: ubuntu-24.04-arm
            target-platform: linux-aarch64
    steps:
      - uses: actions/checkout@v4
      - name: Build as2_msgs package
        id: build_msgs
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: as2_msgs/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} --package-format tar-bz2 -c conda-forge -c robostack-staging
          artifact-name: ros-humble-as2-msgs-${{ matrix.target-platform }}

      - name: Build as2_core package
        id: build_core
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: as2_core/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} --package-format tar-bz2 -c conda-forge -c robostack-staging
          artifact-name: ros-humble-as2-core-${{ matrix.target-platform }}

      - name: Build as2_cli package
        id: build_cli
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: as2_cli/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} --package-format tar-bz2 -c conda-forge -c robostack-staging
          artifact-name: ros-humble-as2-cli-${{ matrix.target-platform }}

      - name: Build as2_state_estimator package
        id: build_state_estimator
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: as2_state_estimator/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} --package-format tar-bz2 -c conda-forge -c robostack-staging
          artifact-name: ros-humble-as2-state-estimator-${{ matrix.target-platform }}
