name: Build as2_core and as2_msgs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: macos-latest
            target-platform: osx-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build as2_msgs conda package
        id: build_msgs
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: as2_msgs/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} --package-format tar-bz2 -c conda-forge -c robostack-staging
          artifact-name: ros-humble-as2_msgs-${{ matrix.target-platform }}

      - name: Build as2_core conda package
        id: build_core
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: as2_core/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} --package-format tar-bz2 -c conda-forge -c robostack-staging
          artifact-name: ros-humble-as2_core-${{ matrix.target-platform }}
